// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportPlanner.Data;

#nullable disable

namespace SportPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220234029_LinkConceptsToItinerary")]
    partial class LinkConceptsToItinerary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportPlanner.Models.ApplicationUser", b =>
                {
                    b.Property<string>("SupabaseId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("SupabaseId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ConceptCategories");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConceptCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<int>("TacticalComplexity")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalComplexity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConceptCategoryId");

                    b.HasIndex("SportId");

                    b.HasIndex("Name", "SportId")
                        .IsUnique();

                    b.ToTable("ConceptTemplates");
                });

            modelBuilder.Entity("SportPlanner.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("SportPlanner.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("SportPlanner.Models.MethodologicalItinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentItineraryId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentItineraryId");

                    b.HasIndex("TeamCategoryId");

                    b.ToTable("MethodologicalItineraries");
                });

            modelBuilder.Entity("SportPlanner.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerSupabaseId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("SportPlanner.Models.OrganizationMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserSupabaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserSupabaseId")
                        .IsUnique();

                    b.ToTable("OrganizationMemberships");
                });

            modelBuilder.Entity("SportPlanner.Models.PlanConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<int>("SportConceptId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SportConceptId");

                    b.HasIndex("PlanningId", "SportConceptId")
                        .IsUnique();

                    b.ToTable("PlanConcepts");
                });

            modelBuilder.Entity("SportPlanner.Models.PlaningScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourtId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("PlanningId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("TrainingScheduleDays");
                });

            modelBuilder.Entity("SportPlanner.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("SportPlanner.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("SportPlanner.Models.SportConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConceptCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConceptTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DevelopmentLevel")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MethodologicalItineraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SportId")
                        .HasColumnType("integer");

                    b.Property<int>("TacticalComplexity")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalDifficulty")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalTacticalFocus")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConceptCategoryId");

                    b.HasIndex("ConceptTemplateId");

                    b.HasIndex("MethodologicalItineraryId");

                    b.HasIndex("SportId");

                    b.HasIndex("Name", "SportId");

                    b.ToTable("SportConcepts");
                });

            modelBuilder.Entity("SportPlanner.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetentionEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserSupabaseId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("SportId");

                    b.HasIndex("OrganizationId", "SportId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscription_Org_Sport_Active")
                        .HasFilter("\"IsActive\" = TRUE AND \"OrganizationId\" IS NOT NULL");

                    b.HasIndex("UserSupabaseId", "SportId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscription_User_Sport_Active")
                        .HasFilter("\"IsActive\" = TRUE AND \"UserSupabaseId\" IS NOT NULL");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Subscription_UserOrOrg", "(\"UserSupabaseId\" IS NOT NULL) != (\"OrganizationId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SportPlanner.Models.SubscriptionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<string>("ChangedByUserSupabaseId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NewPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("OldPlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionHistories");
                });

            modelBuilder.Entity("SportPlanner.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxMembersPerTeam")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("SportPlanner.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentTacticalLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTechnicalLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerUserSupabaseId")
                        .HasColumnType("text");

                    b.Property<int?>("SportId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SportId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TeamCategoryId");

                    b.HasIndex("TeamLevelId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SportPlanner.Models.TeamCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("TeamCategories");
                });

            modelBuilder.Entity("SportPlanner.Models.TeamLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamLevels");
                });

            modelBuilder.Entity("SportPlanner.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserSupabaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "UserSupabaseId")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptCategory", b =>
                {
                    b.HasOne("SportPlanner.Models.ConceptCategory", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptTemplate", b =>
                {
                    b.HasOne("SportPlanner.Models.ConceptCategory", "ConceptCategory")
                        .WithMany()
                        .HasForeignKey("ConceptCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportPlanner.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConceptCategory");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportPlanner.Models.MethodologicalItinerary", b =>
                {
                    b.HasOne("SportPlanner.Models.MethodologicalItinerary", "ParentItinerary")
                        .WithMany("ChildItineraries")
                        .HasForeignKey("ParentItineraryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportPlanner.Models.TeamCategory", "TeamCategory")
                        .WithMany()
                        .HasForeignKey("TeamCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentItinerary");

                    b.Navigation("TeamCategory");
                });

            modelBuilder.Entity("SportPlanner.Models.OrganizationMembership", b =>
                {
                    b.HasOne("SportPlanner.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SportPlanner.Models.PlanConcept", b =>
                {
                    b.HasOne("SportPlanner.Models.Planning", "Planning")
                        .WithMany("PlanConcepts")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPlanner.Models.SportConcept", "SportConcept")
                        .WithMany()
                        .HasForeignKey("SportConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planning");

                    b.Navigation("SportConcept");
                });

            modelBuilder.Entity("SportPlanner.Models.PlaningScheduleDay", b =>
                {
                    b.HasOne("SportPlanner.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportPlanner.Models.Planning", "Planning")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("SportPlanner.Models.Planning", b =>
                {
                    b.HasOne("SportPlanner.Models.Team", "Team")
                        .WithMany("Plannings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportPlanner.Models.SportConcept", b =>
                {
                    b.HasOne("SportPlanner.Models.ConceptCategory", "ConceptCategory")
                        .WithMany()
                        .HasForeignKey("ConceptCategoryId");

                    b.HasOne("SportPlanner.Models.ConceptTemplate", "ConceptTemplate")
                        .WithMany("Concepts")
                        .HasForeignKey("ConceptTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportPlanner.Models.MethodologicalItinerary", "MethodologicalItinerary")
                        .WithMany("Concepts")
                        .HasForeignKey("MethodologicalItineraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportPlanner.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.Navigation("ConceptCategory");

                    b.Navigation("ConceptTemplate");

                    b.Navigation("MethodologicalItinerary");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportPlanner.Models.Subscription", b =>
                {
                    b.HasOne("SportPlanner.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportPlanner.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportPlanner.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportPlanner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserSupabaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");

                    b.Navigation("Plan");

                    b.Navigation("Sport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportPlanner.Models.SubscriptionHistory", b =>
                {
                    b.HasOne("SportPlanner.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SportPlanner.Models.Team", b =>
                {
                    b.HasOne("SportPlanner.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId");

                    b.HasOne("SportPlanner.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.HasOne("SportPlanner.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("SportPlanner.Models.TeamCategory", "TeamCategory")
                        .WithMany()
                        .HasForeignKey("TeamCategoryId");

                    b.HasOne("SportPlanner.Models.TeamLevel", "TeamLevel")
                        .WithMany()
                        .HasForeignKey("TeamLevelId");

                    b.Navigation("Organization");

                    b.Navigation("Sport");

                    b.Navigation("Subscription");

                    b.Navigation("TeamCategory");

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("SportPlanner.Models.TeamCategory", b =>
                {
                    b.HasOne("SportPlanner.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportPlanner.Models.TeamMember", b =>
                {
                    b.HasOne("SportPlanner.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SportPlanner.Models.ConceptTemplate", b =>
                {
                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("SportPlanner.Models.MethodologicalItinerary", b =>
                {
                    b.Navigation("ChildItineraries");

                    b.Navigation("Concepts");
                });

            modelBuilder.Entity("SportPlanner.Models.Planning", b =>
                {
                    b.Navigation("PlanConcepts");

                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("SportPlanner.Models.Team", b =>
                {
                    b.Navigation("Plannings");
                });
#pragma warning restore 612, 618
        }
    }
}
